In [3]:
#NumPy : Numerical Python
# Faster and Easy Maths
import numpy as np

List vs Numpy : Time Taken

In [2]:
from time import process_time

#Lists
lst = [i for i in range(10**8)]
start_time = process_time()
lst = [i+5 for i in lst]
end_time = process_time()
print(end_time - start_time)

#Numpy Arrays
arr = np.array([i for i in range(10**8)])
start_time = process_time()
arr = arr + 5
end_time = process_time()
print(end_time - start_time)

6.3426735899999995
0.23720661200000137


Numpy Arrays

In [6]:
#Lists
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

#Numpy Arrays
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# 1D and 2D Arrays
a = np.array([1,2,3,4,5])
a.shape

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

#Changing Datatype
b = np.array([(1,2,3,4),(2,3,4,5)],dtype=float)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]]


Initial Placeholders in NumPy Arrays

In [14]:
#Zeros Array
a = np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#Ones Array
b = np.ones((5,6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
#Particular Value
b = np.full((4,5),5)
print(b)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [16]:
#Random Values b/w 0 and 1
c = np.random.random((3,4))
print(c)

[[0.87467799 0.71954532 0.15362287 0.79172083]
 [0.5344414  0.09555681 0.51716585 0.92943823]
 [0.67730955 0.01424612 0.92438358 0.56742091]]


In [18]:
#Randdom Integers
d = np.random.randint(0,100,(4,5))
print(d)

[[30 91 83 11 81]
 [24 41 38 86 78]
 [ 4  9 47 96 19]
 [81 30 79 60 31]]


In [20]:
#Identity Maxtrix
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
#Evenly Spaced
e = np.linspace(10,20,6)
print(e)

[10. 12. 14. 16. 18. 20.]


In [27]:
#List to Numpy Array
list1 = [1,2,3,4,5]
np_array = np.asarray(list1)
print(np_array)
np_array.shape
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analyzing Numpy Arrays

In [29]:
c = np.random.randint(10,20,(4,5))
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(4, 5)
2
20
int64


Mathematical Operations

In [35]:
a = np.random.randint(0,10,(3,2))
b = np.random.randint(10,20,(3,2))

print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")
print(a/b,"\n")

list1 = [1,2,3]
list2 = [4,5,6]

print(list1+list2)

[[22 18]
 [18 18]
 [13 20]] 

[[-16  -8]
 [-10 -16]
 [ -9  -2]] 

[[57 65]
 [56 17]
 [22 99]] 

[[0.15789474 0.38461538]
 [0.28571429 0.05882353]
 [0.18181818 0.81818182]] 

[1, 2, 3, 4, 5, 6]


In [37]:
print(np.add(a,b),"\n")
print(np.subtract(a,b),"\n")
print(np.multiply(a,b),"\n")
print(np.divide(a,b),"\n")

[[22 18]
 [18 18]
 [13 20]] 

[[-16  -8]
 [-10 -16]
 [ -9  -2]] 

[[57 65]
 [56 17]
 [22 99]] 

[[0.15789474 0.38461538]
 [0.28571429 0.05882353]
 [0.18181818 0.81818182]] 



Array Manipulation

In [42]:
a = np.random.randint(0,10,(2,4))
print(a)

#transpose
b = np.transpose(a)
print()
print(b)
print(b.shape)

c = a.T
print()
print(c)
c.shape

[[4 8 0 1]
 [7 2 5 7]]

[[4 7]
 [8 2]
 [0 5]
 [1 7]]
(4, 2)

[[4 7]
 [8 2]
 [0 5]
 [1 7]]


(4, 2)

In [52]:
#Reshaping an Array
a = np.random.randint(0,10,(5,6))
print(a,"\n")
print(a.shape)

print()
a = a.reshape(6,5)
print(a)
print(a.shape)

[[3 4 6 3 3 5]
 [0 1 1 4 3 3]
 [4 1 7 9 5 1]
 [9 3 1 8 3 9]
 [7 1 9 1 1 7]] 

(5, 6)

[[3 4 6 3 3]
 [5 0 1 1 4]
 [3 3 4 1 7]
 [9 5 1 9 3]
 [1 8 3 9 7]
 [1 9 1 1 7]]
(6, 5)
